services:
  chat-bi-api:
    image: chat-bi-api:v1.0.0
    container_name: chat-bi-api
    ports:
      - '13000:13000'
    env_file:
      - ../.env
    restart: unless-stopped
    networks:
      - chat-bi-app
    depends_on:
      - chat-bi-frontend

  chat-bi-frontend:
    container_name: chat-bi-frontend
    image: chat-bi-frontend:v1.0.0
    network_mode: "host"  # 使用host网络模式
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  chat-bi-app:
    driver: bridge
