services:
  app:
    image: chat-bi:v1.0.0
    container_name: chat-bi
    ports:
      - "13000:8000"
    environment:
      - DB_HOST=172.22.220.64
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=admin123456
      - DB_NAME=chat_bi
      - MILVUS_HOST=172.22.220.64
      - MILVUS_PORT=19530
      - OPENAI_API_KEY=sk-
      - HTTP_PROXY="http://172.22.220.64:7890"
      - HTTPS_PROXY="http://172.22.220.64:7890"
    restart: unless-stopped
